sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
script:
  - bundle exec foodcritic -f any --tags ~FC003 --tags ~FC015 --tags ~FC023 .
  - bundle exec rubocop
  - bundle exec rspec --color --format progress
