---
name: md-links

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  md-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
        with:
          use-verbose-mode: 'yes'
          folder-path: 'documentation'
          config-file: .github/workflows/mlc_config.json
